### ISSUE TITLE
Exception missing details in the Quarkus/GraalVM native executable context

### ISSUE THREAD

**Issue by zeppelinux** [AdoptOpenJDK/openjdk-aarch64-jdk8u#4]
I have [Quarkus app]([https://github.com/zeppelinux/quarked-ddns](https://github.com/zeppelinux/quarked-ddns)) that uses XPath. When it is compiled to native code and fails throwing this exception:
https://github.com/AdoptOpenJDK/openjdk-aarch64-jdk8u/blob/4ec2083f190ea2e818aa35d67920ce2d952dfdf3/jaxp/src/com/sun/org/apache/xml/internal/utils/ObjectPool.java#L144
It is not clear what is the problem, i.e. is it because of missing resource or something else that should be explicitly included during the build.

The stacktrace looks like this:

        Suppressed: java.lang.RuntimeException: exception creating new instance for pool
                at com.sun.org.apache.xml.internal.utils.ObjectPool.getInstance(ObjectPool.java:144)
                at com.sun.org.apache.xml.internal.utils.StringBufferPool.get(StringBufferPool.java:45)
                at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getStringValue(DOM2DTM.java:822)
                at com.sun.org.apache.xpath.internal.objects.XNodeSet.getStringFromNode(XNodeSet.java:219)
                at com.sun.org.apache.xpath.internal.objects.XNodeSet.str(XNodeSet.java:282)
                at com.sun.org.apache.xpath.internal.jaxp.XPathImplUtil.getResultAsType(XPathImplUtil.java:147)
                at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:81)
                at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:89)
                at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:111)
                at com.diligesoft.qddns.vendors.XPathAndRegexVendor.extract(XPathAndRegexVendor.java:35)
                at com.diligesoft.qddns.routes.VendorsRoute.lambda$configure$2(VendorsRoute.java:61)
                at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66)
                at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:780)
                at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:688)

**Comment by zeppelinux** [comment]
not sure if this is the right place, closing

**Comment by karianna** [comment]
@zeppelinux You're best off to join our Slack community (adoptopenjdk.net/slack) and try the support channel there.
